[2023-08-21 18:34:16,902] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: entregable3.extract_data manual__2023-08-20T13:28:24.762691+00:00 [queued]>
[2023-08-21 18:34:16,926] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: entregable3.extract_data manual__2023-08-20T13:28:24.762691+00:00 [queued]>
[2023-08-21 18:34:16,928] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-08-21 18:34:16,938] {taskinstance.py:1377} INFO - Starting attempt 2 of 6
[2023-08-21 18:34:16,939] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-08-21 18:34:16,969] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): extract_data> on 2023-08-20 13:28:24.762691+00:00
[2023-08-21 18:34:16,978] {standard_task_runner.py:52} INFO - Started process 3515 to run task
[2023-08-21 18:34:16,983] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'entregable3', 'extract_data', 'manual__2023-08-20T13:28:24.762691+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/entregable.py', '--cfg-path', '/tmp/tmp7yo7_vxl', '--error-file', '/tmp/tmpwhapaf6l']
[2023-08-21 18:34:16,985] {standard_task_runner.py:80} INFO - Job 12: Subtask extract_data
[2023-08-21 18:34:17,092] {task_command.py:371} INFO - Running <TaskInstance: entregable3.extract_data manual__2023-08-20T13:28:24.762691+00:00 [running]> on host eebeded14cb4
[2023-08-21 18:34:17,216] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Yamil
AIRFLOW_CTX_DAG_ID=entregable3
AIRFLOW_CTX_TASK_ID=extract_data
AIRFLOW_CTX_EXECUTION_DATE=2023-08-20T13:28:24.762691+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-08-20T13:28:24.762691+00:00
[2023-08-21 18:34:21,711] {python.py:173} INFO - Done. Returned value was:        id     player_name  player_age  games  ...  turnovers  points  team  season
0    2796    Nikola Jokić          27     20  ...         70     600   DEN    2023
1    2864    Jimmy Butler          33     22  ...         41     592   MIA    2023
2    2754    Jayson Tatum          24     20  ...         56     543   BOS    2023
3    2795    Jamal Murray          25     20  ...         50     522   DEN    2023
4    2755    Jaylen Brown          26     20  ...         66     453   BOS    2023
..    ...             ...         ...    ...  ...        ...     ...   ...     ...
389  2467     Earl Barron          29      1  ...          0       0   POR    2011
390  2361  Andrés Nocioni          31      1  ...          1       0   PHI    2011
391  2503       Joe Smith          35      5  ...          0       0   LAL    2011
392  2504     Luke Walton          30      1  ...          2       0   LAL    2011
393  2532     Etan Thomas          32      1  ...          0       0   ATL    2011

[394 rows x 12 columns]
[2023-08-21 18:34:21,764] {xcom.py:586} ERROR - Could not serialize the XCom value into JSON. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your *** config.
[2023-08-21 18:34:21,765] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 68, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2412, in xcom_push
    session=session,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 68, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 198, in set
    map_index=map_index,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 583, in serialize_value
    return json.dumps(value).encode('UTF-8')
  File "/usr/local/lib/python3.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type DataFrame is not JSON serializable
[2023-08-21 18:34:21,782] {taskinstance.py:1420} INFO - Marking task as UP_FOR_RETRY. dag_id=entregable3, task_id=extract_data, execution_date=20230820T132824, start_date=20230821T183416, end_date=20230821T183421
[2023-08-21 18:34:21,810] {standard_task_runner.py:97} ERROR - Failed to execute job 12 for task extract_data (Object of type DataFrame is not JSON serializable; 3515)
[2023-08-21 18:34:21,843] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-08-21 18:34:21,920] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
