[2023-08-22 14:36:37,561] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: entregable3.extract_and_transform_data manual__2023-08-22T14:36:35.688963+00:00 [queued]>
[2023-08-22 14:36:37,576] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: entregable3.extract_and_transform_data manual__2023-08-22T14:36:35.688963+00:00 [queued]>
[2023-08-22 14:36:37,577] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-08-22 14:36:37,591] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2023-08-22 14:36:37,594] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-08-22 14:36:37,621] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): extract_and_transform_data> on 2023-08-22 14:36:35.688963+00:00
[2023-08-22 14:36:37,629] {standard_task_runner.py:52} INFO - Started process 3819 to run task
[2023-08-22 14:36:37,634] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'entregable3', 'extract_and_transform_data', 'manual__2023-08-22T14:36:35.688963+00:00', '--job-id', '37', '--raw', '--subdir', 'DAGS_FOLDER/entregable.py', '--cfg-path', '/tmp/tmp_hidifly', '--error-file', '/tmp/tmp71locs8a']
[2023-08-22 14:36:37,636] {standard_task_runner.py:80} INFO - Job 37: Subtask extract_and_transform_data
[2023-08-22 14:36:37,737] {task_command.py:371} INFO - Running <TaskInstance: entregable3.extract_and_transform_data manual__2023-08-22T14:36:35.688963+00:00 [running]> on host eebeded14cb4
[2023-08-22 14:36:37,854] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Yamil
AIRFLOW_CTX_DAG_ID=entregable3
AIRFLOW_CTX_TASK_ID=extract_and_transform_data
AIRFLOW_CTX_EXECUTION_DATE=2023-08-22T14:36:35.688963+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-08-22T14:36:35.688963+00:00
[2023-08-22 14:36:45,389] {logging_mixin.py:115} INFO - No hay nuevos datos para cargar.
[2023-08-22 14:36:45,390] {python.py:173} INFO - Done. Returned value was: None
[2023-08-22 14:36:45,406] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=entregable3, task_id=extract_and_transform_data, execution_date=20230822T143635, start_date=20230822T143637, end_date=20230822T143645
[2023-08-22 14:36:45,462] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-08-22 14:36:45,516] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
