[2023-08-22 14:31:09,433] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: entregable3.extract_and_transform_data manual__2023-08-22T14:31:07.641022+00:00 [queued]>
[2023-08-22 14:31:09,447] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: entregable3.extract_and_transform_data manual__2023-08-22T14:31:07.641022+00:00 [queued]>
[2023-08-22 14:31:09,447] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-08-22 14:31:09,463] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2023-08-22 14:31:09,465] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-08-22 14:31:09,495] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): extract_and_transform_data> on 2023-08-22 14:31:07.641022+00:00
[2023-08-22 14:31:09,502] {standard_task_runner.py:52} INFO - Started process 3461 to run task
[2023-08-22 14:31:09,508] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'entregable3', 'extract_and_transform_data', 'manual__2023-08-22T14:31:07.641022+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/entregable.py', '--cfg-path', '/tmp/tmpt3j02jw7', '--error-file', '/tmp/tmpoqyket2t']
[2023-08-22 14:31:09,509] {standard_task_runner.py:80} INFO - Job 31: Subtask extract_and_transform_data
[2023-08-22 14:31:09,606] {task_command.py:371} INFO - Running <TaskInstance: entregable3.extract_and_transform_data manual__2023-08-22T14:31:07.641022+00:00 [running]> on host eebeded14cb4
[2023-08-22 14:31:09,720] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Yamil
AIRFLOW_CTX_DAG_ID=entregable3
AIRFLOW_CTX_TASK_ID=extract_and_transform_data
AIRFLOW_CTX_EXECUTION_DATE=2023-08-22T14:31:07.641022+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-08-22T14:31:07.641022+00:00
[2023-08-22 14:31:17,521] {logging_mixin.py:115} INFO - No hay nuevos datos para cargar.
[2023-08-22 14:31:17,523] {python.py:173} INFO - Done. Returned value was: None
[2023-08-22 14:31:17,544] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=entregable3, task_id=extract_and_transform_data, execution_date=20230822T143107, start_date=20230822T143109, end_date=20230822T143117
[2023-08-22 14:31:17,639] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-08-22 14:31:17,697] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
