[2023-08-22 14:28:39,214] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: entregable3.extract_and_transform_data manual__2023-08-22T14:28:37.049234+00:00 [queued]>
[2023-08-22 14:28:39,243] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: entregable3.extract_and_transform_data manual__2023-08-22T14:28:37.049234+00:00 [queued]>
[2023-08-22 14:28:39,244] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-08-22 14:28:39,245] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2023-08-22 14:28:39,248] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-08-22 14:28:39,290] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): extract_and_transform_data> on 2023-08-22 14:28:37.049234+00:00
[2023-08-22 14:28:39,302] {standard_task_runner.py:52} INFO - Started process 3304 to run task
[2023-08-22 14:28:39,334] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'entregable3', 'extract_and_transform_data', 'manual__2023-08-22T14:28:37.049234+00:00', '--job-id', '27', '--raw', '--subdir', 'DAGS_FOLDER/entregable.py', '--cfg-path', '/tmp/tmp9qopp1q2', '--error-file', '/tmp/tmp3oksa1l8']
[2023-08-22 14:28:39,337] {standard_task_runner.py:80} INFO - Job 27: Subtask extract_and_transform_data
[2023-08-22 14:28:39,495] {task_command.py:371} INFO - Running <TaskInstance: entregable3.extract_and_transform_data manual__2023-08-22T14:28:37.049234+00:00 [running]> on host eebeded14cb4
[2023-08-22 14:28:39,630] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Yamil
AIRFLOW_CTX_DAG_ID=entregable3
AIRFLOW_CTX_TASK_ID=extract_and_transform_data
AIRFLOW_CTX_EXECUTION_DATE=2023-08-22T14:28:37.049234+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-08-22T14:28:37.049234+00:00
[2023-08-22 14:28:47,439] {logging_mixin.py:115} INFO - No hay nuevos datos para cargar.
[2023-08-22 14:28:47,440] {python.py:173} INFO - Done. Returned value was: None
[2023-08-22 14:28:47,457] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=entregable3, task_id=extract_and_transform_data, execution_date=20230822T142837, start_date=20230822T142839, end_date=20230822T142847
[2023-08-22 14:28:47,495] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-08-22 14:28:47,551] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
