[2023-08-24 19:23:14,622] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: entregable3.extract_and_transform_data manual__2023-08-24T19:23:12.666893+00:00 [queued]>
[2023-08-24 19:23:14,637] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: entregable3.extract_and_transform_data manual__2023-08-24T19:23:12.666893+00:00 [queued]>
[2023-08-24 19:23:14,638] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-08-24 19:23:14,651] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2023-08-24 19:23:14,652] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-08-24 19:23:14,672] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): extract_and_transform_data> on 2023-08-24 19:23:12.666893+00:00
[2023-08-24 19:23:14,685] {standard_task_runner.py:52} INFO - Started process 10168 to run task
[2023-08-24 19:23:14,689] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'entregable3', 'extract_and_transform_data', 'manual__2023-08-24T19:23:12.666893+00:00', '--job-id', '92', '--raw', '--subdir', 'DAGS_FOLDER/entregable3.py', '--cfg-path', '/tmp/tmp88ruf_am', '--error-file', '/tmp/tmpnrqgzte1']
[2023-08-24 19:23:14,691] {standard_task_runner.py:80} INFO - Job 92: Subtask extract_and_transform_data
[2023-08-24 19:23:14,799] {task_command.py:371} INFO - Running <TaskInstance: entregable3.extract_and_transform_data manual__2023-08-24T19:23:12.666893+00:00 [running]> on host eebeded14cb4
[2023-08-24 19:23:14,927] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Yamil
AIRFLOW_CTX_DAG_ID=entregable3
AIRFLOW_CTX_TASK_ID=extract_and_transform_data
AIRFLOW_CTX_EXECUTION_DATE=2023-08-24T19:23:12.666893+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-08-24T19:23:12.666893+00:00
[2023-08-24 19:23:22,561] {logging_mixin.py:115} INFO - No hay nuevos datos para cargar.
[2023-08-24 19:23:22,561] {python.py:173} INFO - Done. Returned value was: None
[2023-08-24 19:23:22,592] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=entregable3, task_id=extract_and_transform_data, execution_date=20230824T192312, start_date=20230824T192314, end_date=20230824T192322
[2023-08-24 19:23:22,644] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-08-24 19:23:22,686] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
